// No "use client" here!
import Footer from "./Footer/Footer";
import "./globals.css";
import HeaderWrapper from "./HeaderWrapper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <HeaderWrapper />
        {children}
        <Footer />
      </body>
    </html>
  );
}
